[features]
seeds = false
[programs.localnet]
messaging = "6Jc6kj1M6kpntJKk9zZSuLd4skaD2SfdnRuxCxhTnD3i"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/siddh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
